# Syntax highlighting
highlighter:         pygments

# Permalinks
permalink:           /:categories/:title

# Setup
baseurl:             ""
title:               Alexis Boissonnat
tagline:             My personal website
url:                 http://boissonnat.github.io
markdown:            kramdown

# Assets
sass:
  sass_dir: _scss
  style: compressed
